object frmMain: TfrmMain
  Left = 0
  Top = 0
  Caption = 'Main'
  ClientHeight = 743
  ClientWidth = 1021
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -12
  Font.Name = 'Segoe UI'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 15
  object pnlHeader: TPanel
    Left = 0
    Top = 0
    Width = 1021
    Height = 65
    Align = alTop
    TabOrder = 0
    object btnRegisterPeople: TBitBtn
      Left = 1
      Top = 1
      Width = 80
      Height = 63
      Align = alLeft
      Caption = 'Cadastrar'
      Glyph.Data = {
        F6060000424DF606000000000000360000002800000018000000180000000100
        180000000000C0060000B0000000B00000000000000000000000FFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFDF6EAFBE8C9FAE6C6FAE5C5FAE4C5FAE3C4
        F9E2C3F9E1C2F9E0C1F8DFC0F8DEBFF8DDBEF7DCBDF7DBBCF7DBBEFBEEE1FFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCEACAF4C164F5C879F5C679F4
        C377F4C175F3BE73F2BC71F1B96EF1B76CF0B56AEFB268EEAF65EDAD64EDAA61
        EBA65CE69139F5D4B2FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8D288FBE4
        BAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFF4CFA7EBA45BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFF9D282FCECCEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8DEC1EAA051FFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFF9D589FCEBC9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7DBBBECA7
        5BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFADDA0FBE4B3FFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFF4CC9EF0B87AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCECC9F8D1
        7FFFFFFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFEFEEEAD5DF6D6B0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFEFCF8D17CFBE7BBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7D6ABEEAB57FEFBF8FFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFDF5E2F7CD71FBE7BCFFFFFEFFFEFBFCECCC
        F9DBA1F7D18DF7CF8BF7D69DFAE7C8FFFDFBFFFEFEF8D9AFEFAB50FBEAD4FFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDF4DEF8D280F8
        D17EF8CC71F8CF7BFAE0ABFBE6C0FBE6C0F9DCA9F4C474F2BA62F3BD6CF2B867
        FBEAD3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFDFAFDF0D5FDF4E1FFFFFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD
        F2E0FBE9CEFEFCF8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEF8EBFBE0AAF9D68DF8D2
        88FADDA8FDF6E9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCECCAF7CB6D
        FADC9EFCEBC8FCEAC5F9D898F5C366FBE7C4FFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE
        F4E0F8CE71FDF1D6FFFFFFFFFFFFFFFFFFFFFFFFFDEFD4F5C467FDF1DBFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFADC98FBE6B5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA
        E1AEF8D38EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFEFDF8D175FEF7E8FFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFEF5E4F6C667FFFFFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFCF8D072FEFAF2FFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFAF0F7C766FFFEFBFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9
        D784FDF1D5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDEFD3F8CF7AFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFBE8BAF9DB91FFFEFCFFFFFFFFFFFFFFFFFFFFFFFFFFFEFBF8
        D383FBE5B5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFCF9DC92FADE9AFEF8EBFFFFFFFFFF
        FFFEF7E9FAD88FF9D68AFFFDF8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDF9FBE3AB
        F8D276F9D683F9D684F8CF71FBE1A8FFFCF6FFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFCF5FDF3DAFDF3DCFFFCF7FFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF}
      Layout = blGlyphTop
      TabOrder = 0
      OnClick = btnRegisterPeopleClick
    end
  end
  object pnlFooter: TPanel
    Left = 0
    Top = 680
    Width = 1021
    Height = 63
    Align = alBottom
    TabOrder = 1
  end
  object pnlMain: TPanel
    Left = 0
    Top = 65
    Width = 1021
    Height = 615
    Align = alClient
    TabOrder = 2
  end
end
